name = "DataTreatments"
uuid = "1b3ff5f2-9b56-42a2-b38a-76a033f741ca"
version = "0.2.3"
authors = ["Michele Ghiotti", "Federico Manzella", "Riccardo Pasini"]

[deps]
Catch22 = "acdeb78f-3d39-4310-8fdf-6d75c17c6d5a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Normalization = "be38d6a3-8366-4a42-ad57-222272b5bbe7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extensions]
NormalizationExt = "Normalization"

[compat]
Catch22 = "0.7"
DataFrames = "1"
LinearAlgebra = "1"
Normalization = "0.9"
Reexport = "1.2.2"
Statistics = "1"
StatsBase = "0.34"
julia = "1"

[extras]
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
SoleData = "123f1ae1-6307-4526-ab5b-aab3a92a2b8c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MLJ", "SoleData", "Test"]
