name = "DataTreatments"
uuid = "1b3ff5f2-9b56-42a2-b38a-76a033f741ca"
version = "0.0.4-DEV"
authors = ["Riccardo Pasini"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataFrames = "1.8"
Statistics = "1.11"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
