name = "DataTreatments"
uuid = "1b3ff5f2-9b56-42a2-b38a-76a033f741ca"
version = "0.0.5-DEV"
authors = ["Riccardo Pasini"]

[deps]
Catch22 = "acdeb78f-3d39-4310-8fdf-6d75c17c6d5a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Catch22 = "0.7"
DataFrames = "1.8"
Statistics = "1.11"
StatsBase = "0.34.8"
julia = "1"

[extras]
Normalization = "be38d6a3-8366-4a42-ad57-222272b5bbe7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Normalization", "Test"]
